# Generated by Django 5.2.2 on 2025-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_content",
            field=models.CharField(max_length=500),
        ),
    ]
